<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Masuk</name>
   <tag></tag>
   <elementGuidId>6db97882-4567-4045-9d1d-754f0d7f1c42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.slicknav_nav > span.align-middle > a.mybtn.btn.header-btn.text-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='modalLoginShow()'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>498ebc59-bd49-4f05-8114-0fbb59251b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mybtn btn header-btn text-white</value>
      <webElementGuid>d2204c03-6fb8-44ec-9e0a-ebb0a761afaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>modalLoginShow()</value>
      <webElementGuid>8233558e-02d5-42c2-b116-e702da4feca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>0d23e956-61e5-4814-9cbb-71401b1a9830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;sizes customelements history pointerevents postmessage webgl websockets cssanimations csscolumns csscolumns-width csscolumns-span csscolumns-fill csscolumns-gap csscolumns-rule csscolumns-rulecolor csscolumns-rulestyle csscolumns-rulewidth csscolumns-breakbefore csscolumns-breakafter csscolumns-breakinside flexbox picture srcset webworkers&quot;]/body[1]/header[1]/div[1]/div[@class=&quot;header-area header-transparrent&quot;]/div[@class=&quot;main-header header-sticky&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;mobile_menu d-block d-lg-none&quot;]/div[@class=&quot;slicknav_menu&quot;]/ul[@class=&quot;slicknav_nav&quot;]/span[@class=&quot;align-middle&quot;]/a[@class=&quot;mybtn btn header-btn text-white&quot;]</value>
      <webElementGuid>e2b7d16b-0afc-473c-b89e-799ddf91baf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='modalLoginShow()'])[2]</value>
      <webElementGuid>7d032dd1-df20-40b8-8875-c2bc25cacc09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Masuk')])[2]</value>
      <webElementGuid>e5e95c2e-ba0f-4a2f-a673-9aef4823a67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kontak Kami'])[2]/following::a[1]</value>
      <webElementGuid>fb714a36-1946-4b6b-b3a4-e962ef4dbebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari Lowongan'])[2]/following::a[2]</value>
      <webElementGuid>1c4f32b7-9514-4c7c-b4c8-38cff538133a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[2]/preceding::a[1]</value>
      <webElementGuid>be431de0-38f5-4037-970b-5011b91b7639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recruit-MEIkuti &amp; Rasakan'])[1]/preceding::a[2]</value>
      <webElementGuid>a0eb62ce-17c9-4829-8fee-75e06e557111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/span/a</value>
      <webElementGuid>af3c6925-7e90-408a-868e-dc2f39132723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>71662040-79ca-470c-a224-4e3b69300c20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
